---
title: COM 674
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")

f <- function (x) {formatC(x, format="d", big.mark=',')}
bold <- function(x) {paste('{\\textbf{',x,'}}', sep ='')}
gray <- function(x) {paste('{\\textcolor{gray}{',x,'}}', sep ='')}
wrapify <- function (x) {paste("{", x, "}", sep="")}
p <- function (x) {formatC(x, format='f', digits=1, big.mark=',')}
```

<style type="text/css">

/* Changes to RevealJS default formatting.

I prefer this style but you can change these to your preferences */

/* This bit lets you do columns */
.container{
  display: flex;
}

.col{
  flex: 1;
}

.reveal section img{
border: none;
background: none;
box-shadow: none;
}

.highlight {
color: LightCoral;
}

.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
text-transform: none;
}

.reveal h1 {
margin-top:200px;
}

div.footnote {
font-size: 40%;
text-align: right;
}

.bg-image{
width: 180px;
}

.reveal .slides section .fragment.fade-in-then-out,
.reveal .slides section .fragment.current-visible {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-out.current-fragment,
  .reveal .slides section .fragment.current-visible.current-fragment {
    opacity: 1;
    visibility: inherit; }

.reveal .slides section .fragment.fade-in-then-semi-out {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-semi-out.visible {
    opacity: 0.5;
    visibility: inherit; }
  .reveal .slides section .fragment.fade-in-then-semi-out.current-fragment {
    opacity: 1;
visibility: inherit; }

</style>

## Dad Joke

Interviewer: "Where do you see yourself in 5 years?"

Me: "Listening. I would say listening is my biggest weakness."


## Online 674

> - FlipGrid
>	- Discussion of readings
>	- Programming questions?
> - Assignments
> - Lectures and example code
> - Do what you can, and I'll do the same

## Adjustments to schedule

> - Text analysis to next week
> - Screen scraping to the end
> - This includes readings, so LMK if that messes up your schedule
> - Planning document feedback by Friday

## API assignments

> - Goal is to take you through the whole process with a simple question
> - I will work on some solutions + video
> - Good approach for bigger API-based projects
>	- 3 scripts:
>		- First gets raw data and saves it
>		- Second processes it into a CSV
>		- Third creates measures, plots, etc.
>	- Make your process reproducible

## Cleaning data

> - Why is data 'dirty'?
>	- Errors in transcription
>	- Bugs in software that produced it
>	- Missing data (e.g., when a date is unknown it's recoded as Jan 1)
>	- Can't be read by software
>	  - Wrong date format
>	  - Multiple age formats - e.g., '4', '4 yo', '4 years'
>	- Observations that shouldn't be in the analysis
>	- Inappropriate for statistical tests
>	  - log-transformations
>	  - Coding groups (e.g., high-risk and low-risk)

## Operationalization

> - Making a construct measurable
>	- Constructs are not empirical and can't be tested directly
>	- We must argue that our measures represent or at least are correlated with the concepts we really care about
>	- Hypotheses relate concepts together, e.g., "socially cohesive groups are more willing to contribute to shared goals"
>	- In order to test this, need to argue that you have something that represents social cohesion, and something that represents shared goals.

## Online data

> - Online data is "raw"
>	- This is generally wonderful - we have actual conversations, full text, etc.
> - However, it isn't made for researchers
>	- It isn't designed to measure a construct
>	- We have to do the work to create measures that measure them (and recognize when we can't)

## Thanks

> - Stay safe
> - Stay inside
