---
pagetitle: Week 2
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: false
    reveal_plugins: ["notes"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")

f <- function (x) {formatC(x, format="d", big.mark=',')}
bold <- function(x) {paste('{\\textbf{',x,'}}', sep ='')}
gray <- function(x) {paste('{\\textcolor{gray}{',x,'}}', sep ='')}
wrapify <- function (x) {paste("{", x, "}", sep="")}
p <- function (x) {formatC(x, format='f', digits=1, big.mark=',')}
```

<style type="text/css">

/* Changes to RevealJS default formatting.

I prefer this style but you can change these to your preferences */

/* This bit lets you do columns */
.container{
  display: flex;
}

.col{
  flex: 1;
}

.reveal section img{
border: none;
background: none;
box-shadow: none;
}

.highlight {
color: LightCoral;
}

.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
text-transform: none;
}

.reveal h1 {
margin-top:200px;
}

div.footnote {
font-size: 40%;
text-align: right;
}

.bg-image{
width: 180px;
}

.reveal .slides section .fragment.fade-in-then-out,
.reveal .slides section .fragment.current-visible {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-out.current-fragment,
  .reveal .slides section .fragment.current-visible.current-fragment {
    opacity: 1;
    visibility: inherit; }

.reveal .slides section .fragment.fade-in-then-semi-out {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-semi-out.visible {
    opacity: 0.5;
    visibility: inherit; }
  .reveal .slides section .fragment.fade-in-then-semi-out.current-fragment {
    opacity: 1;
visibility: inherit; }

</style>

# Week 2

# Things I should have mentioned last week

## The wiki and the class
> - Based on other courses, some wiki content overlaps with course at University of Washington
>	- There may be inconsistencies or errors
>	- If you can, fix them! 

## Brightspace

> - Readings
> - Discussion board
> - Example Projects


## Additional Readings

> - Sign up sheet
> - What do we want this to look like?

## Project Options

> - I'm compiling some example projects
> - Whatever is most valuable for you
>	- Methods + result section of paper
>	- Jupyter notebook
>	- Replication

## Random participation

```{python, echo=T}
seed = 121
import pandas as pd

names = pd.read_csv('../class_list.csv')

shuffled_names = names.sample(frac=1,random_state = seed).Name.values

shuffled_names[0]

```

## Random participation

> - Slightly scary way to encourage mutual accountability
> - Helps add diversity to our discussion
> - Passing is OK

## Bit By Bit

> - Did the distinction between "readymade" and "custommade" data resonate with you?
>	- Where does the line blur between these two types?
>	- How does this distinction differ from the quantitative/qualitative dichotomy?

## Bit By Bit

> - Would you rather read more of this book or read more example papers?

## Programming Principles Review

> - What is a string?
> - What is the difference between RAM and a hard drive?
> - What is a variable?
>- What is an interactive python prompt? How is that different from a program file?
> - What do you still have questions about?
