---
title: COM 674
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: false
    reveal_plugins: ["notes"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")

f <- function (x) {formatC(x, format="d", big.mark=',')}
bold <- function(x) {paste('{\\textbf{',x,'}}', sep ='')}
gray <- function(x) {paste('{\\textcolor{gray}{',x,'}}', sep ='')}
wrapify <- function (x) {paste("{", x, "}", sep="")}
p <- function (x) {formatC(x, format='f', digits=1, big.mark=',')}
```

<style type="text/css">

/* Changes to RevealJS default formatting.

I prefer this style but you can change these to your preferences */

/* This bit lets you do columns */
.container{
  display: flex;
}

.col{
  flex: 1;
}

.reveal section img{
border: none;
background: none;
box-shadow: none;
}

.highlight {
color: LightCoral;
}

.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
text-transform: none;
}

.reveal h1 {
margin-top:200px;
}

div.footnote {
font-size: 40%;
text-align: right;
}

.bg-image{
width: 180px;
}

.reveal .slides section .fragment.fade-in-then-out,
.reveal .slides section .fragment.current-visible {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-out.current-fragment,
  .reveal .slides section .fragment.current-visible.current-fragment {
    opacity: 1;
    visibility: inherit; }

.reveal .slides section .fragment.fade-in-then-semi-out {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-semi-out.visible {
    opacity: 0.5;
    visibility: inherit; }
  .reveal .slides section .fragment.fade-in-then-semi-out.current-fragment {
    opacity: 1;
visibility: inherit; }

</style>

## Weekly Dad Joke

Bro, can you hand me that leaflet?

Brochure

## Housekeeping

> - Project proposal feedback session?

## Course feedback

> - Sharing/comparing code
>	- Solutions?
>	- Feedback
>	- Screencast?
> - Synchronous exercises in class
> - More lecture

## Solution sharing

Chapter 7: 1,2,3

Baby names: 1, 2, 3

## Paper discussion

Margolin, D. B., Hannak, A., & Weber, I. (2018). Political Fact-Checking on Twitter: When Do Corrections Have an Effect? Political Communication, 35(2), 196–219.

> - Lots of evidence that people don't act like "intuitive scientists"
>	- Misinformation doesn't change opinions
>	- Rumors propagation happens even in the face of corrections
> - Key question of their study:
>	- What are the social conditions that encourage retraction/opinion change?

## Hypotheses

> - H1: People are more likely to accept corrections from friends
> - H2: People are more likely to accept corrections from those embedded in same group (larger shared audience)
> - RQ: How do audience sizes affect likelihood to accept corrections?

## Paper discussion

> - Method
>	- Twitter "garden hose" to identify tweets where:
>	  - "Snopee" shares misinformation
>	  - "Snoper" shares link to correction
>	  - "Snopee" responds
>	- Coded the content of the correction and response
>	- Regression to predict when a correction was accepted
> - H1 was accepted; no strong effect for others.

## Questions

> - What were some strengths of the research design? Weaknesses?
> - What is the next study you would design to complement this study?
> - How much do you think the context influenced the results?

## Project proposal feedback session?




## Principles for this week

> - Jupyter Notebooks
> - Dictionaries
> - Tuples

## Team problem

Day 2 challenges - #7

## Homework

> - Jupyter notebook + problems from book
