---
title: COM 674
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: false
    reveal_plugins: ["notes"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")

f <- function (x) {formatC(x, format="d", big.mark=',')}
bold <- function(x) {paste('{\\textbf{',x,'}}', sep ='')}
gray <- function(x) {paste('{\\textcolor{gray}{',x,'}}', sep ='')}
wrapify <- function (x) {paste("{", x, "}", sep="")}
p <- function (x) {formatC(x, format='f', digits=1, big.mark=',')}
```

<style type="text/css">

/* Changes to RevealJS default formatting.

I prefer this style but you can change these to your preferences */

/* This bit lets you do columns */
.container{
  display: flex;
}

.col{
  flex: 1;
}

.reveal section img{
border: none;
background: none;
box-shadow: none;
}

.highlight {
color: LightCoral;
}

.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
text-transform: none;
}

.reveal h1 {
margin-top:200px;
}

div.footnote {
font-size: 40%;
text-align: right;
}

.bg-image{
width: 180px;
}

.reveal .slides section .fragment.fade-in-then-out,
.reveal .slides section .fragment.current-visible {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-out.current-fragment,
  .reveal .slides section .fragment.current-visible.current-fragment {
    opacity: 1;
    visibility: inherit; }

.reveal .slides section .fragment.fade-in-then-semi-out {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-semi-out.visible {
    opacity: 0.5;
    visibility: inherit; }
  .reveal .slides section .fragment.fade-in-then-semi-out.current-fragment {
    opacity: 1;
visibility: inherit; }

</style>

## Weekly Dad Joke

I accidentally swallowed a bunch of scrabble tiles.


My next trip to the bathroom could spell disaster.

## Housekeeping


## Solution sharing

Jupyter notebook exercise

Chapter 9: 2, 3

Chapter 10: 1, 2

## Paper discussion (Courteney)

Benefield, G. A., Shen, C., & Leavitt, A. (2016). Virtual Team Networks: How Group Social Capital Affects Team Success in a Massively Multiplayer Online Game. Proceedings of the 19th ACM Conference on Computer-Supported Cooperative Work & Social Computing, 679–690. 


## Principles for this week

> - pandas
> - dataframes
> - Visualization

## Team problem

Day 2 challenges - #7

## Homework

> - Jupyter notebook 
> - Start "Intermediate Python"
