---
title: Day 12
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: false
    css: ../../libs/css/custom_css.css
    lib_dir: ../../libs
    allow_uptree_lib_dir: True
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = './')

f <- function (x) {formatC(x, format="d", big.mark=',')}
bold <- function(x) {paste('{\\textbf{',x,'}}', sep ='')}
gray <- function(x) {paste('{\\textcolor{gray}{',x,'}}', sep ='')}
wrapify <- function (x) {paste("{", x, "}", sep="")}
p <- function (x) {formatC(x, format='f', digits=1, big.mark=',')}
```

## Dad Joke

Did you hear about the mathematician who was afraid of negative numbers?

<span class='fragment'>
He would stop at nothing to avoid them
</span>

## Housekeeping

> - No class on Tuesday
> - Finally finished SAR feedback
> - IRB Discussion
> - Ask for help
> - Rough draft for peer feedback on December 1?


## Principles for code organization

> - 3 directories
>	- code
>	- data
>	- paper


## Reproducible workflows and best practices

> - The idea is to be able to fix any step in the workflow and have the rest run with minimal problems
>	- Data updates
>	- Bugs
>	- Changes to measures or questions
> - Save raw data
> - Run code in order
> - Write comments! (or text in Jupyter)
> - Advanced mode: Makefiles, knitr

## Paper Discussion

DellaPosta, D., Shi, Y., & Macy, M. (2015). Why Do Liberals Drink Lattes? American Journal of Sociology, 120(5), 1473–1511.


## Why isn't politics just about policies?

> - We all have stereotypes about what conservatives and liberals are like
> - What do conservatives wear?
> - What cars do liberals drive?
> - In some cases, these are more correlated with party than policy issues!

## Explaining correlations rely on a search for explanations

> - E.g., liberals were more likely to believe in astrology
>	- Why? Maybe because it is seen as superstitious/sacrilegious? 
> - But a similar just-so story could be told if the correlation went the other way
>	- Conservatives have a more magical / less scientific worldview

## What's the answer? People are part of networks!

> - "Alignment [is an] emergent property of a self-organizing cultural landscape"
> - We want to be more like the people who we see as our group
>	- Social influence: we change our beliefs/opinions/behaviors
>	- Homophily: we change who we are connected to and connect to those more like us
> - Result is networks that are autocorrelated

## Simulation Model

> - Agents are given 25 random "opinions" of 1/0
> - The (observed - expected) Euclidian distance is the weight between them
> - Agents probabilisitically adopt beliefs of neighbors based on similarity

## Even when opinions are correlated with demographics, it could be network autocorrelation that causes both


## Agent-based modeling is neat

> - Using computational agents
> - Test theory
>	- Can agents acting according to theory produce what we see empirically?
> - Tool for thinking
>	- How might we expect changes to relate to higher level dynamics?

## HW Review
> - Wrong branch of the class cloned - oops!
